### ISSUE TITLE
TiDB Operator Architecture & design document

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#651] opened 2019-07-11 06:56 UTC

**Comment by gregwebs** [comment] 2019-07-12 02:51
This seems like a duplicate of #63. I have some good slides about this now.

**Comment by weekface** [comment] 2019-07-23 03:49
https://github.com/pingcap/docs-cn/pull/1625

**Comment by aylei** [comment] 2019-08-09 04:05
closed via https://github.com/pingcap/docs-cn/pull/1625

**Closed by aylei** 2019-08-09 04:05 UTC
Labels: doc
