### ISSUE TITLE
pd start failed when node failover

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#230] opened 2018-12-14 11:52 UTC
when a node shutdown cause a pd member offline and then we auto start a new pd member[example-pd-3 ] to make failover. but the new pd member start failed. 

- pods status
```
[tidb@172.16.30.59 ~]$ kubectl get po -n example -o wide
NAME                               READY     STATUS             RESTARTS   AGE       IP              NODE
example-monitor-7bc8cdb97b-29rlq   2/2       Terminating        0          32m       10.128.47.39    172.16.30.58
example-monitor-7bc8cdb97b-4f8rj   2/2       Running            0          16m       10.128.32.153   172.16.30.59
example-pd-0                       1/1       Running            1          26m       10.128.32.146   172.16.30.59
example-pd-1                       1/1       Terminating        0          26m       10.128.47.58    172.16.30.58
example-pd-2                       1/1       Running            2          27m       10.128.34.113   172.16.30.98
example-pd-3                       0/1       CrashLoopBackOff   6          10m       10.128.32.167   172.16.30.59
example-tidb-0                     1/1       Running            0          21m       10.128.32.147   172.16.30.59
example-tidb-1                     1/1       Running            0          22m       10.128.34.72    172.16.30.98
example-tikv-0                     2/2       Running            0          22m       10.128.34.127   172.16.30.98
example-tikv-1                     2/2       Terminating        0          24m       10.128.47.54    172.16.30.58
example-tikv-2                     2/2       Running            0          25m       10.128.32.130   172.16.30.59
example-tikv-3                     2/2       Running            0          6m        10.128.34.65    172.16.30.98
```

- example-pd-3 's log

```
starting pd-server ...
/pd-server --data-dir=/var/lib/pd --name=example-pd-3 --peer-urls=http://0.0.0.0:2380 --advertise-peer-urls=http://example-pd-3.example-pd-peer.example.svc:2380 --client-urls=http://0.0.0.0:2379 --advertise-client-urls=http://example-pd-3.example-pd-peer.example.svc:2379 --config=/etc/pd/pd.toml --join=http://example-pd-0.example-pd-peer.example.svc:2380,http://example-pd-1.example-pd-peer.example.svc:2380,http://example-pd-2.example-pd-peer.example.svc:2380
2018/12/14 11:26:11.937 util.go:56: [info] Welcome to Placement Driver (PD).
2018/12/14 11:26:11.937 util.go:57: [info] Release Version: v2.1.0
2018/12/14 11:26:11.937 util.go:58: [info] Git Commit Hash: 757e91d4bf3df047a8953f239c7c2eb2aea6e7e1
2018/12/14 11:26:11.937 util.go:59: [info] Git Branch: release-2.1
2018/12/14 11:26:11.937 util.go:60: [info] UTC Build Time:  2018-11-30 11:36:10
2018/12/14 11:26:11.937 metricutil.go:79: [info] disable Prometheus push client
2018/12/14 11:26:11.937 join.go:179: [error] failed to open:open /var/lib/pd/member: no such file or directory
2018/12/14 11:26:11.937 grpclog.go:45: [info] parsed scheme: ""
2018/12/14 11:26:11.937 grpclog.go:45: [info] scheme "" not registered, fallback to default scheme
2018/12/14 11:26:11.937 grpclog.go:45: [info] ccResolverWrapper: sending new addresses to cc: [{example-pd-0.example-pd-peer.example.svc:2380 0  <nil>}]
2018/12/14 11:26:11.937 grpclog.go:45: [info] balancerWrapper: got update addr from Notify: [{example-pd-0.example-pd-peer.example.svc:2380 <nil>} {example-pd-1.example-pd-peer.example.svc:2380 <nil>} {example-pd-2.example-pd-peer.example.svc:2380 <nil>}]

2018/12/14 11:26:11.950 grpclog.go:45: [info] balancerWrapper: got update addr from Notify: [{example-pd-2.example-pd-peer.example.svc:2380 <nil>}]

2018/12/14 11:26:11.954 grpclog.go:60: [warning] Failed to dial example-pd-0.example-pd-peer.example.svc:2380: grpc: the connection is closing; please retry.
2018/12/14 11:26:11.955 grpclog.go:45: [info] balancerWrapper: got update addr from Notify: []

2018/12/14 11:26:11.955 grpclog.go:45: [info] balancerWrapper: got update addr from Notify: [{example-pd-0.example-pd-peer.example.svc:2380 <nil>} {example-pd-1.example-pd-peer.example.svc:2380 <nil>}]

2018/12/14 11:26:11.955 main.go:75: [fatal] join error etcdserver: unhealthy cluster
github.com/pingcap/pd/pkg/etcdutil.AddEtcdMember
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:79
github.com/pingcap/pd/server.PrepareJoinCluster
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/join.go:141
main.main
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/cmd/pd-server/main.go:73
runtime.main
	/usr/local/go/src/runtime/proc.go:201
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

- the pd version:
```
/ # /pd-server -V
Release Version: v2.1.0
Git Commit Hash: 757e91d4bf3df047a8953f239c7c2eb2aea6e7e1
Git Branch: release-2.1
UTC Build Time:  2018-11-30 11:36:10
```

**Comment by nolouch** [comment] 2018-12-14 12:04
@xiaojingchen join should all member are health.

**Comment by xiaojingchen** [comment] 2018-12-14 12:12
@nolouch I thought only one member unhealthy, the pd cluster is still usable.
in fact, the new pd member join success after some time.

**Comment by aylei** [comment] 2019-11-15 04:37
It is by design of PD
closing

**Closed by aylei** 2019-11-15 04:37 UTC
Labels: test/stability, type/bug
