### ISSUE TITLE
The failure message in backup status is overwhelming

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1657] opened 2020-02-08 10:06 UTC
## Bug Report

**What version of TiDB Operator are you using?**

`2e566a0379b47eeedaac72897daedbb97515920c`

**What did you do?**

Took a backup using `br` and failed, inspect the status of `backup` object to reason why.

**What did you expect to see?**
A reasonable error reason in  `.status.message`

**What did you see instead?**
An overwhelming error message:

[status.tar.gz](https://github.com/pingcap/tidb-operator/files/4174035/status.tar.gz)

**Comment by shuijing198799** [comment] 2020-03-30 10:10
file is broken and can't reproduced, discussed with aylei @aylei  close it.

**Closed** 2020-03-31 06:07 UTC
Labels: priority:P2, type/bug
