### ISSUE TITLE
Tidb-operator cannot scale out tikv from 2 to 3 by itself.

### ISSUE THREAD

**Issue by cvvz** [pingcap/tidb-operator#3229] opened 2020-09-07 03:14 UTC
## Bug Report

**What did you do?**

As I mentioned in https://github.com/pingcap/tidb-operator/issues/3182, if you scale in tikv from 3 to 2 and then want to scale out back to 3, it cannot be done.

According to the logs of tidb-controller:
```shell
I0906 17:12:05.189967       1 tikv_scaler.go:68] scaling out tikv statefulset tidb-cluster/backdb-tikv, ordinal: 2 (replicas: 3, delete slots: [])
I0906 17:12:05.204073       1 tidb_cluster_controller.go:303] TidbCluster: tidb-cluster/backdb, still need sync: tikv.ScaleOut, cluster tidb-cluster/backdb ready to scale out, wait for next round, requeuing
```
It is because the controller is waiting for the PVC of `tikv-2` to be deleted. Which will never happen because the scale-in-tikv-to-2 operation is forbiden. 

**What did you expect to see?**
Scale out from 2 to 3 successfully.

**What did you see instead?**
Fail to scale out from 2 to 3.

**Comment by DanielZhangQD** [comment] 2020-09-07 03:18
@cvvz Could you please attach the log of the tidb-controller-manager?
We'd like to check why the scaleout is blocked.

**Comment by cvvz** [comment] 2020-09-07 03:21
@DanielZhangQD The logs have been added, and I think It is because the controller is waiting for the PVC of `tikv-2` to be deleted. Which will never happen because the scale-in-tikv-to-2 operation is forbiden.

**Comment by DanielZhangQD** [comment] 2020-09-07 03:57
OK, here is the root cause:
During the scale in, after the store for TiKV is removed, the PVC of the Pod will be appended a `tidb.pingcap.com/pvc-defer-deleting` annotation indicating that it can be deleted.
During scale-out, the Operator will check the PVC of the new Pod and will try to delete the PVC, if the annotation `tidb.pingcap.com/pvc-defer-deleting` exists, it will delete the PVC and scale out the StatefulSet, if the annotation does not exist, it will just requeue.
So this issue is actually caused by the failure of scaling in, because the scaling in cannot finish so that the annotation is not added to the PVC and it cannot be deleted by the Operator which blocks the scaling out logic.

So after #3182 is done, this issue should be addressed too.

**Comment by DanielZhangQD** [comment] 2021-01-06 05:41
Close this since https://github.com/pingcap/tidb-operator/issues/3182 has been fixed and users cannot scale in TiKV from 3 to 2.

**Closed by DanielZhangQD** 2021-01-06 05:41 UTC
