### ISSUE TITLE
TiKV leaders can't be moved back to the node whose downtime reaches max-store-down-time

### ISSUE THREAD

**Issue by coderplay** [pingcap/tidb-operator#4483] opened 2022-03-17 21:49 UTC
## Bug Report

**Problem Statement**

We have encountered a scenario in a 3 TiKV nodes setup:
1. When one of the TiKV nodes was taken down for longer than [max-store-down-time](https://docs.pingcap.com/tidb/stable/pd-configuration-file#max-store-down-time), all of the node's leaders were transferred to the remaining 2 nodes. Meanwhile, because there are only 2 nodes left, the lost replicas can't be recovered, and each TiKV region has lost one replica.
2. The replicas would be recovered if the node was brought back, but the # of leaders on the node would be stick to zero.
3. No leader transfer from the TiKV node to other nodes has been observed. Nothing had transpired after two days of waiting.

**Analysis**

This is actually a bug from tidb-operator. In order to make TiKV rolling upgrade more graceful,  the TiDB operator adds a leader evictor  (i.e. evict-leaders-scheduler) to the to be upgraded TiKV pod. This evictor moves the region leaders out from upgrading TiKV pod to other pods. The evictor may not be deleted at the end if there is a problem with the TiKV pod upgrade or if the TiDB operator faces exceptions somehow. As a result, the TiKV pod's region leaders are unable to move back.

We cannot assume that this upgrade always takes the happy path. There is no way out when an unhappy path is taken.

**Comment by DanielZhangQD** [comment] 2022-03-18 09:46
@coderplay Could you please list the operations you did to help reproduce this issue?
I did not reproduce it in our clusters.

**Comment by DanielZhangQD** [comment] 2022-03-18 10:05
@coderplay Thanks for reporting this issue!
I found a scenario where the evict leader scheduler will be left in the PD:
1. Suppose 3 TiKVs in the cluster, update the image or configuration of TiKV in the TidbCluster CR, TiDB Operator will add an evict leader scheduler for the store of tikv-2 and PD will begin to evict leader from that store.
2. ***Before* all the leaders are transferred, revert the changes, in this case, TiDB Operator will not execute the upgrade logic because no need to upgrade from the current situation, so the evict leader scheduler of tikv-2 will not be deleted.

We will fix this in the next release.

**Closed** 2022-05-13 10:00 UTC
