### ISSUE TITLE
Some metrics of TiDB are missing

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb-operator#3606] opened 2020-12-15 06:17 UTC
## Bug Report

**What did you do?**
Start a brand new cluster. 

**What did you expect to see?**
CPU monitor in TiDB dashboard is work normally.

**What did you see instead?**
<img width="936" alt="Screen Shot 2020-12-15 at 2 11 04 PM" src="https://user-images.githubusercontent.com/35896542/102178057-b168da00-3edf-11eb-9393-59e7d70a5380.png">

This is because the job field is changed when writing into Prometheus. We should not change the job name in operator.

Workaround: manually change it to the pod name, it becomes ok.

**Comment by DanielZhangQD** [comment] 2020-12-15 08:51
@mikechengwei This seems to be caused by https://github.com/pingcap/tidb-operator/pull/3543/files, please help check it.

**Comment by DanielZhangQD** [comment] 2020-12-15 09:06
The job name has changed from:
![image](https://user-images.githubusercontent.com/36026334/102193961-ad48b680-3ef7-11eb-86f6-59e96a83a98b.png)
to
![image](https://user-images.githubusercontent.com/36026334/102193941-a7eb6c00-3ef7-11eb-826a-03841f79338b.png)

But the job name is fixed in the grafana dashboards:
```
tidb.json:              "expr": "(time() - process_start_time_seconds{job=\"tidb\"})",
tidb.json:              "expr": "process_resident_memory_bytes{job=\"tidb\"}",
tidb.json:              "expr": "go_memstats_heap_sys_bytes{job=\"tidb\"}",
```

**Comment by mikechengwei** [comment] 2020-12-15 09:48
I think use job name bind to grafana json is not a graceful style. We need to sure monitoring data includes component label, cluster label and namespace label and replace the grafana json file with these labels.

**Comment by DanielZhangQD** [comment] 2020-12-28 02:00
Close via https://github.com/pingcap/tidb-operator/pull/3622 and https://github.com/pingcap/monitoring/pull/84.

**Closed by DanielZhangQD** 2020-12-28 02:00 UTC
Labels: type/bug
